name: SmartDNS-CN

on:
  push:
  schedule:
    - cron: '45 19 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Actions/Checkout
      uses: actions/checkout@main


    - name: Download Rules
      run: |
        cd smartdns_cn_rules
        curl  "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/direct-list.txt"  > /etc/smartdns/cn.conf
        curl  "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/apple-cn.txt"    >> /etc/smartdns/cn.conf
        curl  "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/google-cn.txt"   >> /etc/smartdns/cn.conf
        sh rules.sh

    - name: Commit
      run: |
        git config --global user.email touma@dymy.org
        git config --global user.name BlackTouma
        git add .
        git commit -m "update" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
